spring:
  main:
    allow-bean-definition-overriding: true

  profiles:
    active:
      - local

client:
  viacep:
    url: https://viacep.com.br/ws

#logging:
#  level:
#    io:
#      awspring:
#        cloud: debug